/**
 * Maps ISO 3166-1 numeric codes (used in world-atlas TopoJSON)
 * to ISO 3166-1 alpha-3 codes (used in regulation JSON data).
 *
 * Source: ISO 3166-1 standard.
 * Coverage: All 177 countries present in world-atlas/countries-110m.json.
 *
 * Also re-exports US state name lookups for unified display name resolution.
 */

export const numericToAlpha3: Record<string, string> = {
  '004': 'AFG',
  '008': 'ALB',
  '010': 'ATA',
  '012': 'DZA',
  '024': 'AGO',
  '031': 'AZE',
  '032': 'ARG',
  '036': 'AUS',
  '040': 'AUT',
  '044': 'BHS',
  '050': 'BGD',
  '051': 'ARM',
  '056': 'BEL',
  '064': 'BTN',
  '068': 'BOL',
  '070': 'BIH',
  '072': 'BWA',
  '076': 'BRA',
  '084': 'BLZ',
  '090': 'SLB',
  '096': 'BRN',
  '100': 'BGR',
  '104': 'MMR',
  '108': 'BDI',
  '112': 'BLR',
  '116': 'KHM',
  '120': 'CMR',
  '124': 'CAN',
  '140': 'CAF',
  '144': 'LKA',
  '148': 'TCD',
  '152': 'CHL',
  '156': 'CHN',
  '170': 'COL',
  '178': 'COG',
  '180': 'COD',
  '188': 'CRI',
  '191': 'HRV',
  '192': 'CUB',
  '196': 'CYP',
  '203': 'CZE',
  '204': 'BEN',
  '208': 'DNK',
  '214': 'DOM',
  '218': 'ECU',
  '222': 'SLV',
  '226': 'GNQ',
  '231': 'ETH',
  '232': 'ERI',
  '233': 'EST',
  '242': 'FJI',
  '246': 'FIN',
  '250': 'FRA',
  '260': 'ATF',
  '262': 'DJI',
  '266': 'GAB',
  '268': 'GEO',
  '270': 'GMB',
  '275': 'PSE',
  '276': 'DEU',
  '288': 'GHA',
  '296': 'KIR',
  '300': 'GRC',
  '304': 'GRL',
  '320': 'GTM',
  '324': 'GIN',
  '328': 'GUY',
  '332': 'HTI',
  '340': 'HND',
  '348': 'HUN',
  '352': 'ISL',
  '356': 'IND',
  '360': 'IDN',
  '364': 'IRN',
  '368': 'IRQ',
  '372': 'IRL',
  '376': 'ISR',
  '380': 'ITA',
  '384': 'CIV',
  '388': 'JAM',
  '392': 'JPN',
  '398': 'KAZ',
  '400': 'JOR',
  '404': 'KEN',
  '408': 'PRK',
  '410': 'KOR',
  '414': 'KWT',
  '417': 'KGZ',
  '418': 'LAO',
  '422': 'LBN',
  '426': 'LSO',
  '428': 'LVA',
  '430': 'LBR',
  '434': 'LBY',
  '440': 'LTU',
  '442': 'LUX',
  '450': 'MDG',
  '454': 'MWI',
  '458': 'MYS',
  '462': 'MDV',
  '466': 'MLI',
  '470': 'MLT',
  '478': 'MRT',
  '480': 'MUS',
  '484': 'MEX',
  '496': 'MNG',
  '498': 'MDA',
  '504': 'MAR',
  '508': 'MOZ',
  '512': 'OMN',
  '516': 'NAM',
  '524': 'NPL',
  '528': 'NLD',
  '540': 'NCL',
  '548': 'VUT',
  '554': 'NZL',
  '558': 'NIC',
  '562': 'NER',
  '566': 'NGA',
  '578': 'NOR',
  '586': 'PAK',
  '591': 'PAN',
  '598': 'PNG',
  '600': 'PRY',
  '604': 'PER',
  '608': 'PHL',
  '616': 'POL',
  '620': 'PRT',
  '624': 'GNB',
  '626': 'TLS',
  '630': 'PRI',
  '634': 'QAT',
  '642': 'ROU',
  '643': 'RUS',
  '646': 'RWA',
  '682': 'SAU',
  '686': 'SEN',
  '694': 'SLE',
  '702': 'SGP',
  '703': 'SVK',
  '704': 'VNM',
  '705': 'SVN',
  '706': 'SOM',
  '710': 'ZAF',
  '716': 'ZWE',
  '724': 'ESP',
  '728': 'SSD',
  '729': 'SDN',
  '732': 'ESH',
  '740': 'SUR',
  '748': 'SWZ',
  '752': 'SWE',
  '756': 'CHE',
  '760': 'SYR',
  '762': 'TJK',
  '764': 'THA',
  '768': 'TGO',
  '780': 'TTO',
  '784': 'ARE',
  '788': 'TUN',
  '792': 'TUR',
  '795': 'TKM',
  '800': 'UGA',
  '804': 'UKR',
  '807': 'MKD',
  '818': 'EGY',
  '826': 'GBR',
  '834': 'TZA',
  '840': 'USA',
  '854': 'BFA',
  '858': 'URY',
  '860': 'UZB',
  '862': 'VEN',
  '887': 'YEM',
  '894': 'ZMB',
};

export const alpha3ToName: Record<string, string> = {
  AFG: 'Afghanistan',
  ALB: 'Albania',
  ATA: 'Antarctica',
  DZA: 'Algeria',
  AGO: 'Angola',
  AZE: 'Azerbaijan',
  ARG: 'Argentina',
  AUS: 'Australia',
  AUT: 'Austria',
  BHS: 'Bahamas',
  BGD: 'Bangladesh',
  ARM: 'Armenia',
  BEL: 'Belgium',
  BTN: 'Bhutan',
  BOL: 'Bolivia',
  BIH: 'Bosnia and Herzegovina',
  BWA: 'Botswana',
  BRA: 'Brazil',
  BLZ: 'Belize',
  SLB: 'Solomon Islands',
  BRN: 'Brunei',
  BGR: 'Bulgaria',
  MMR: 'Myanmar',
  BDI: 'Burundi',
  BLR: 'Belarus',
  KHM: 'Cambodia',
  CMR: 'Cameroon',
  CAN: 'Canada',
  CAF: 'Central African Republic',
  LKA: 'Sri Lanka',
  TCD: 'Chad',
  CHL: 'Chile',
  CHN: 'China',
  COL: 'Colombia',
  COG: 'Republic of the Congo',
  COD: 'Democratic Republic of the Congo',
  CRI: 'Costa Rica',
  HRV: 'Croatia',
  CUB: 'Cuba',
  CYP: 'Cyprus',
  CZE: 'Czech Republic',
  BEN: 'Benin',
  DNK: 'Denmark',
  DOM: 'Dominican Republic',
  ECU: 'Ecuador',
  SLV: 'El Salvador',
  GNQ: 'Equatorial Guinea',
  ETH: 'Ethiopia',
  ERI: 'Eritrea',
  EST: 'Estonia',
  FJI: 'Fiji',
  FIN: 'Finland',
  FRA: 'France',
  ATF: 'French Southern Territories',
  DJI: 'Djibouti',
  GAB: 'Gabon',
  GEO: 'Georgia',
  GMB: 'Gambia',
  PSE: 'Palestine',
  DEU: 'Germany',
  GHA: 'Ghana',
  KIR: 'Kiribati',
  GRC: 'Greece',
  GRL: 'Greenland',
  GTM: 'Guatemala',
  GIN: 'Guinea',
  GUY: 'Guyana',
  HTI: 'Haiti',
  HND: 'Honduras',
  HUN: 'Hungary',
  ISL: 'Iceland',
  IND: 'India',
  IDN: 'Indonesia',
  IRN: 'Iran',
  IRQ: 'Iraq',
  IRL: 'Ireland',
  ISR: 'Israel',
  ITA: 'Italy',
  CIV: 'Ivory Coast',
  JAM: 'Jamaica',
  JPN: 'Japan',
  KAZ: 'Kazakhstan',
  JOR: 'Jordan',
  KEN: 'Kenya',
  PRK: 'North Korea',
  KOR: 'South Korea',
  KWT: 'Kuwait',
  KGZ: 'Kyrgyzstan',
  LAO: 'Laos',
  LBN: 'Lebanon',
  LSO: 'Lesotho',
  LVA: 'Latvia',
  LBR: 'Liberia',
  LBY: 'Libya',
  LTU: 'Lithuania',
  LUX: 'Luxembourg',
  MDG: 'Madagascar',
  MWI: 'Malawi',
  MYS: 'Malaysia',
  MDV: 'Maldives',
  MLI: 'Mali',
  MLT: 'Malta',
  MRT: 'Mauritania',
  MUS: 'Mauritius',
  MEX: 'Mexico',
  MNG: 'Mongolia',
  MDA: 'Moldova',
  MAR: 'Morocco',
  MOZ: 'Mozambique',
  OMN: 'Oman',
  NAM: 'Namibia',
  NPL: 'Nepal',
  NLD: 'Netherlands',
  NCL: 'New Caledonia',
  VUT: 'Vanuatu',
  NZL: 'New Zealand',
  NIC: 'Nicaragua',
  NER: 'Niger',
  NGA: 'Nigeria',
  NOR: 'Norway',
  PAK: 'Pakistan',
  PAN: 'Panama',
  PNG: 'Papua New Guinea',
  PRY: 'Paraguay',
  PER: 'Peru',
  PHL: 'Philippines',
  POL: 'Poland',
  PRT: 'Portugal',
  GNB: 'Guinea-Bissau',
  TLS: 'East Timor',
  PRI: 'Puerto Rico',
  QAT: 'Qatar',
  ROU: 'Romania',
  RUS: 'Russia',
  RWA: 'Rwanda',
  SAU: 'Saudi Arabia',
  SEN: 'Senegal',
  SLE: 'Sierra Leone',
  SGP: 'Singapore',
  SVK: 'Slovakia',
  VNM: 'Vietnam',
  SVN: 'Slovenia',
  SOM: 'Somalia',
  ZAF: 'South Africa',
  ZWE: 'Zimbabwe',
  ESP: 'Spain',
  SSD: 'South Sudan',
  SDN: 'Sudan',
  ESH: 'Western Sahara',
  SUR: 'Suriname',
  SWZ: 'Eswatini',
  SWE: 'Sweden',
  CHE: 'Switzerland',
  SYR: 'Syria',
  TJK: 'Tajikistan',
  THA: 'Thailand',
  TGO: 'Togo',
  TTO: 'Trinidad and Tobago',
  ARE: 'United Arab Emirates',
  TUN: 'Tunisia',
  TUR: 'Turkey',
  TKM: 'Turkmenistan',
  UGA: 'Uganda',
  UKR: 'Ukraine',
  MKD: 'North Macedonia',
  EGY: 'Egypt',
  GBR: 'United Kingdom',
  TZA: 'Tanzania',
  USA: 'United States',
  BFA: 'Burkina Faso',
  URY: 'Uruguay',
  UZB: 'Uzbekistan',
  VEN: 'Venezuela',
  YEM: 'Yemen',
  ZMB: 'Zambia',
};

export { stateCodeToName } from './fipsToStateCode';
export { provinceCodeToName } from './canadianProvinceMap';
