/**
 * Maps US Census Bureau FIPS state codes (used by us-atlas TopoJSON)
 * to ISO 3166-2 subdivision codes and display names.
 */

/** FIPS numeric string → ISO 3166-2 state code */
export const fipsToStateCode: Record<string, string> = {
  '01': 'US-AL',
  '02': 'US-AK',
  '04': 'US-AZ',
  '05': 'US-AR',
  '06': 'US-CA',
  '08': 'US-CO',
  '09': 'US-CT',
  '10': 'US-DE',
  '11': 'US-DC',
  '12': 'US-FL',
  '13': 'US-GA',
  '15': 'US-HI',
  '16': 'US-ID',
  '17': 'US-IL',
  '18': 'US-IN',
  '19': 'US-IA',
  '20': 'US-KS',
  '21': 'US-KY',
  '22': 'US-LA',
  '23': 'US-ME',
  '24': 'US-MD',
  '25': 'US-MA',
  '26': 'US-MI',
  '27': 'US-MN',
  '28': 'US-MS',
  '29': 'US-MO',
  '30': 'US-MT',
  '31': 'US-NE',
  '32': 'US-NV',
  '33': 'US-NH',
  '34': 'US-NJ',
  '35': 'US-NM',
  '36': 'US-NY',
  '37': 'US-NC',
  '38': 'US-ND',
  '39': 'US-OH',
  '40': 'US-OK',
  '41': 'US-OR',
  '42': 'US-PA',
  '44': 'US-RI',
  '45': 'US-SC',
  '46': 'US-SD',
  '47': 'US-TN',
  '48': 'US-TX',
  '49': 'US-UT',
  '50': 'US-VT',
  '51': 'US-VA',
  '53': 'US-WA',
  '54': 'US-WV',
  '55': 'US-WI',
  '56': 'US-WY',
  '60': 'US-AS',
  '66': 'US-GU',
  '69': 'US-MP',
  '72': 'US-PR',
  '78': 'US-VI',
};

/** ISO 3166-2 state code → display name */
export const stateCodeToName: Record<string, string> = {
  'US-AL': 'Alabama',
  'US-AK': 'Alaska',
  'US-AZ': 'Arizona',
  'US-AR': 'Arkansas',
  'US-CA': 'California',
  'US-CO': 'Colorado',
  'US-CT': 'Connecticut',
  'US-DE': 'Delaware',
  'US-DC': 'District of Columbia',
  'US-FL': 'Florida',
  'US-GA': 'Georgia',
  'US-HI': 'Hawaii',
  'US-ID': 'Idaho',
  'US-IL': 'Illinois',
  'US-IN': 'Indiana',
  'US-IA': 'Iowa',
  'US-KS': 'Kansas',
  'US-KY': 'Kentucky',
  'US-LA': 'Louisiana',
  'US-ME': 'Maine',
  'US-MD': 'Maryland',
  'US-MA': 'Massachusetts',
  'US-MI': 'Michigan',
  'US-MN': 'Minnesota',
  'US-MS': 'Mississippi',
  'US-MO': 'Missouri',
  'US-MT': 'Montana',
  'US-NE': 'Nebraska',
  'US-NV': 'Nevada',
  'US-NH': 'New Hampshire',
  'US-NJ': 'New Jersey',
  'US-NM': 'New Mexico',
  'US-NY': 'New York',
  'US-NC': 'North Carolina',
  'US-ND': 'North Dakota',
  'US-OH': 'Ohio',
  'US-OK': 'Oklahoma',
  'US-OR': 'Oregon',
  'US-PA': 'Pennsylvania',
  'US-RI': 'Rhode Island',
  'US-SC': 'South Carolina',
  'US-SD': 'South Dakota',
  'US-TN': 'Tennessee',
  'US-TX': 'Texas',
  'US-UT': 'Utah',
  'US-VT': 'Vermont',
  'US-VA': 'Virginia',
  'US-WA': 'Washington',
  'US-WV': 'West Virginia',
  'US-WI': 'Wisconsin',
  'US-WY': 'Wyoming',
  'US-AS': 'American Samoa',
  'US-GU': 'Guam',
  'US-MP': 'Northern Mariana Islands',
  'US-PR': 'Puerto Rico',
  'US-VI': 'U.S. Virgin Islands',
};
