import { defineMiddleware } from 'astro:middleware';

/**
 * Astro middleware for SSR routes (Radar).
 *
 * vercel.json headers apply only to static assets served by Vercel's CDN.
 * SSR responses are generated by the server function and need headers
 * injected here. Mirrors the same security headers from vercel.json.
 */

export const SECURITY_HEADERS: Record<string, string> = {
  'X-Frame-Options': 'DENY',
  'X-Content-Type-Options': 'nosniff',
  'Referrer-Policy': 'strict-origin-when-cross-origin',
  'Permissions-Policy': 'camera=(), microphone=(), geolocation=()',
  'X-DNS-Prefetch-Control': 'on',
  'Strict-Transport-Security': 'max-age=63072000; includeSubDomains; preload',
  'Content-Security-Policy': [
    "default-src 'none'",
    "script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://va.vercel-scripts.com https://cdn.vercel-insights.com",
    "connect-src 'self' https://www.googletagmanager.com https://www.google-analytics.com https://*.ingest.sentry.io https://vitals.vercel-insights.com",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' https: data:",
    "font-src 'self'",
    "frame-src 'self'",
    "frame-ancestors 'none'",
    "manifest-src 'self'",
    "form-action 'self'",
    "base-uri 'self'",
    'upgrade-insecure-requests',
  ].join('; '),
};

export const onRequest = defineMiddleware(async (_context, next) => {
  const response = await next();

  for (const [key, value] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(key, value);
  }

  return response;
});
